version: "3.8"

services:

  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - $HOME/docker/volumes/postgres/sber2:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_SERVER=${POSTGRES_SERVER}


  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: app
    restart: always
    depends_on:
      - db
    ports:
      - "8001:8001"
    environment:
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - $HOME/docker/volumes/sber2:/var/lib

