"""first migration

Revision ID: 5d8eb1dcf39d
Revises: 
Create Date: 2023-05-12 00:33:04.574193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8eb1dcf39d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('names', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('tlg_link', sa.String(length=256), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('hard_rate', sa.Float(), nullable=True),
    sa.Column('soft_rate', sa.Float(), nullable=True),
    sa.Column('employee', sa.Boolean(), nullable=True),
    sa.Column('stack_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stack_id'], ['stack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('stack')
    # ### end Alembic commands ###
